export const LOCAL_STORAGE_LOGIN_USER_INFO = 'LOCAL_STORAGE_L_U_I';
export const LOCAL_STORAGE_ENGAGEMENT_INFO = 'LOCAL_STORAGE_ENGAGEMENT_INFO';
export const LOCAL_STORAGE_PROPERTY_INFO = 'LOCAL_STORAGE_PROPERTY_INFO';
